name: imprimir datos y filtrar

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  analizando_datos:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: imprimir tabla bruta y neta
        run: |
          echo "tabla desde la fuente"
          cat datos.csv
          echo "filtrando datos"
          grep -iv hotmail | grep -v 15 datos.csv > datos_filtrados.csv

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git stash
          git pull --rebase origin main
          git stash list | grep "stash@{0}" && git stash apply
          git add .
          git diff --cached --exit-code || git commit -m "Add earnings output" --allow-empty
          git push --force-with-lease origin HEAD:main
