name: imprimir datos y filtrar

on:
  schedule:
    - cron: '00 0 * * *' # Runs every day at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  analizando_datos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: imprimir tabla bruta y neta
        run: |
          echo "tabla desde la fuente"
          cat datos.csv
          echo "filtrando datos"
          grep -iv hotmail datos.csv




